# Generated by Django 3.2.13 on 2022-04-24 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smarthome', '0001_squashed_0007_alter_deviceraport_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField(blank=True, null=True)),
                ('solar_radiation', models.FloatField()),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='energygenerator',
            old_name='energy_generation',
            new_name='generation_power',
        ),
        migrations.RenameField(
            model_name='energyreceiver',
            old_name='energy_consumption',
            new_name='device_power',
        ),
        migrations.RemoveField(
            model_name='energygenerator',
            name='efficiency',
        ),
        migrations.AddField(
            model_name='energyreceiver',
            name='supply_voltage',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energystorage',
            name='battery_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_devices', to='smarthome.room'),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='energystorage',
            name='battery_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DevicePowerSupplyRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_from', models.DateTimeField()),
                ('connected_to', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_power_raports', to='smarthome.device')),
                ('energy_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_power_raports', to='smarthome.energyreceiver')),
            ],
        ),
    ]
