# Generated by Django 3.2.12 on 2022-04-10 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smarthome', '0001_squashed_0007_alter_deviceraport_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_devices', to='smarthome.room'),
        ),
        migrations.AlterField(
            model_name='energygenerator',
            name='efficiency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energystorage',
            name='battery_charge',
            field=models.FloatField(),
        ),
    ]
