# Generated by Django 3.2.13 on 2022-04-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_auto_20220424_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_devices', to='smarthome.building'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_devices', to='smarthome.room'),
        ),
    ]
