# Generated by Django 3.2.13 on 2022-05-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_auto_20220425_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energystorage',
            name='battery_charge',
        ),
        migrations.CreateModel(
            name='StorageChargingAndUsageRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_from', models.DateTimeField()),
                ('date_time_to', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_charging_and_usage_raports', to='smarthome.energystorage')),
                ('energy_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage_devices_raports_v2', to='smarthome.energyreceiver')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeStateRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('charge_value', models.FloatField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_state_raports', to='smarthome.energystorage')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUsageRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turned_on', models.DateTimeField()),
                ('turned_off', models.DateTimeField(blank=True, null=True)),
                ('battery_charge', models.FloatField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage_raports', to='smarthome.energystorage')),
                ('energy_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage_devices_raports', to='smarthome.energyreceiver')),
            ],
            options={
                'unique_together': {('device', 'turned_on')},
            },
        ),
        migrations.CreateModel(
            name='StorageChargingRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turned_on', models.DateTimeField()),
                ('turned_off', models.DateTimeField(blank=True, null=True)),
                ('battery_charge', models.FloatField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_charging_raports', to='smarthome.energystorage')),
            ],
            options={
                'unique_together': {('device', 'turned_on')},
            },
        ),
    ]
