# Generated by Django 3.2.13 on 2022-05-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0004_auto_20220503_1255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storageusageraport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storageusageraport',
            name='device',
        ),
        migrations.RemoveField(
            model_name='storageusageraport',
            name='energy_receiver',
        ),
        migrations.AddField(
            model_name='storagechargingandusageraport',
            name='job_type',
            field=models.CharField(choices=[('CH', 'charging'), ('US', 'usage')], default='CH', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='storagechargingandusageraport',
            unique_together={('device', 'date_time_from')},
        ),
        migrations.DeleteModel(
            name='StorageChargingRaport',
        ),
        migrations.DeleteModel(
            name='StorageUsageRaport',
        ),
    ]
