# Generated by Django 3.2.13 on 2022-05-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0005_auto_20220504_1838'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chargestateraport',
            unique_together={('device', 'date')},
        ),
    ]
