# Generated by Django 3.2.13 on 2022-05-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0006_alter_chargestateraport_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevicePowerSupplyRaport',
        ),
    ]
