# Generated by Django 3.2.13 on 2022-05-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0007_delete_devicepowersupplyraport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagechargingandusageraport',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_charging_and_usage_raports', to='smarthome.energystorage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storagechargingandusageraport',
            name='energy_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage_devices_raports_v2', to='smarthome.energyreceiver'),
        ),
    ]
