# Generated by Django 3.2.13 on 2022-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0008_auto_20220519_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagechargingandusageraport',
            name='job_type',
            field=models.CharField(choices=[('CHARGING', 'charging'), ('USAGE', 'usage')], max_length=8),
        ),
    ]
