# Generated by Django 3.2.13 on 2022-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0010_auto_20220611_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagechargingandusageraport',
            name='energy_receiver',
        ),
        migrations.AddField(
            model_name='storagechargingandusageraport',
            name='energy_use',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
